// ⚠️ PLACEHOLDER FILE — DO NOT USE AS-IS.
//
// This file is normally auto-generated by running:
//
//     flutterfire configure
//
// from the root of your Flutter project, after creating a Firebase
// project and installing the FlutterFire CLI. It will overwrite this
// file with your real project's configuration values (API keys, app
// IDs, etc. for Android/iOS/Web).
//
// These values are safe to commit to a public GitHub repo — they are
// not secret keys, they just identify which Firebase project to talk
// to. Access control is enforced by Firestore Security Rules
// (see firestore.rules), not by hiding these values.
//
// Delete this placeholder once `flutterfire configure` regenerates it.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'This starter project targets Android only. '
        'Run `flutterfire configure` to add other platforms.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate them.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO-REPLACE-VIA-FLUTTERFIRE-CONFIGURE',
    appId: 'TODO-REPLACE-VIA-FLUTTERFIRE-CONFIGURE',
    messagingSenderId: 'TODO-REPLACE-VIA-FLUTTERFIRE-CONFIGURE',
    projectId: 'TODO-REPLACE-VIA-FLUTTERFIRE-CONFIGURE',
    storageBucket: 'TODO-REPLACE-VIA-FLUTTERFIRE-CONFIGURE',
  );
}
